### ISSUE TITLE
Adding LLM-Powered-NPCs to FiveM GTA:V

### ISSUE THREAD

**Issue by robertgro** [AkshitIreddy/Interactive-LLM-Powered-NPCs#8]
I wonder if your project could be used to create LLM-Powered-NPCs in the GTA:V FiveM mod, combining it with a simple script like the ones described here [#1](https://forum.cfx.re/t/release-script-to-add-npcs-where-you-want/590801) and here [#2](https://github.com/AlexMihai04/npcs/blob/master/client.lua)?

**Comment by AkshitIreddy** [comment]
this project works externally without communicating directly with the game, the scripts you've linked to seems to show how to add npcs in gta, so after you have added the npcs to the game using the mod you can use this project to talk to them, you don't need to modify the script to tell this project about the npc's name and other info, the project uses facial recognition to figure out who the character is in the frame ( make sure to add all character details with their pictures in the character folder under their name )

**Comment by robertgro** [comment]
Thank you for your explanation @AkshitIreddy. So it seems to be about linking those two projects together. I see if I can spare some time to get a simple setup running as soon as the mod is working for me (https://github.com/citizenfx/fivem/issues/2334).

**Comment by robertgro** [comment]
I'm glad I got the mod working now (forgot to configure the server properly), so I'm able to explore what is possible with the external facial recognition. :)

In case your project needs any additions for this, I'll create a fork of it. I'm closing this issue due to the status is resolved.

**Comment by andysingal** [comment]
How were you able to download the stories from fandom , any scripts ?
